#-------------------------------
# General Site Settings

title: A Jokeful Day
description: A Jokeful Day is dedicated to providing a little bit of sunshine to your day by providing the best and worst jokes around. With hundreds of jokes in our database, enjoy the never-ending new content.
logo: logo.png
icon: icon.png

# Colors
mainAccent: "#ffc955"
grayAccent: "#ebebeb"
textColor: "#292929"

# Navigation
menu:
- {name: One-liner, url: '/One-liner/'}
- {name: Traditional, url: '/Traditional/'}
